FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./

COPY apps/http-backend/package.json apps/http-backend/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/typescript-config/package.json packages/typescript-config/package.json
COPY packages/eslint-config/package.json packages/eslint-config/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN pnpm install --frozen-lockfile

COPY . .

# Prisma only needs DATABASE_URL to exist during generate.
# The real DATABASE_URL will be provided by Kubernetes at runtime.
ENV DATABASE_URL="postgresql://user:password@localhost:5432/dummy"

RUN pnpm --filter @repo/db build
RUN pnpm --filter http-backend build

EXPOSE 3001

CMD ["pnpm", "--filter", "http-backend", "start"]